/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

let num1 = 1,
   sum = (newNum = num2 = 0);
while (true) {
   newNum = num1 + num2;
   num1 = num2;
   num2 = newNum;
   if (newNum <= 4000000) {
      if (newNum % 2 === 0) sum += newNum;
   } else break;
}

console.log(sum);
