/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
const { fib } = require("./util");

let sum = 0;
for (let i = 0; ; i += 1) {
   let newNum = fib(i);
   if (newNum <= 4000000) {
      if (newNum % 2 === 0) sum += newNum;
   } else break;
}

console.log(sum);
